---
#------------------------------------------------------------------------------
# Remove requested items
#------------------------------------------------------------------------------
- name: Ensure Terraform versions absent
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/terraform{{ _terraform_item }}'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_terraform_versions.absent }}'
  loop_control:
    loop_var: _terraform_item
  when: install_terraform_versions.absent is defined
  tags:
    - avinode_devenv_install_terraform

- name: Ensure Terraform symlinks absent
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/{{ _terraform_item }}'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_terraform_versions.absent_symlinks }}'
  loop_control:
    loop_var: _terraform_item
  when: install_terraform_versions.absent_symlinks is defined
  tags:
    - avinode_devenv_install_terraform

- name: Setting Terraform install absent names fact
  set_fact:
    _install_terraform_absent_names: >-
      {{ (install_terraform_versions.absent | map('regex_replace', '^(.*)$', 'terraform\1'))
          + install_terraform_versions.absent_symlinks | list }}
  tags:
    - avinode_devenv_install_terraform

- name: Ensure absent bash completions for Terraform
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/{{ _item }}.sh'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ _install_terraform_absent_names }}'
  loop_control:
    loop_var: _item
  tags:
    - avinode_devenv_install_terraform

- name: Ensure absent Zsh completions for Terraform
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/share/zsh/site-functions/_{{ _item }}'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ _install_terraform_absent_names }}'
  loop_control:
    loop_var: _item
  tags:
    - avinode_devenv_install_terraform


#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- name: Ensure Terraform versions installed
  include_tasks: process-install.yaml
  vars:
    bin_file: '{{ avinode_devenv_prefix }}/bin/terraform{{ _terraform_item }}'
    go_arch: '{{ avinode_devenv_go_arch }}'
    go_platform: '{{ avinode_devenv_go_platform }}'
    version: '{{ _terraform_item }}'
  loop: '{{ install_terraform_versions.installed }}'
  loop_control:
    loop_var: _terraform_item
  when: install_terraform_versions.installed is defined
  tags:
    - avinode_devenv_install_terraform

- name: Ensure Terraform symlinks
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/{{ _terraform_item.key }}'
    src: '{{ avinode_devenv_prefix }}/bin/terraform{{ _terraform_item.value }}'
    state: link
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_terraform_versions.symlinks | dict2items }}'
  loop_control:
    loop_var: _terraform_item
  when: install_terraform_versions.symlinks is defined
  tags:
    - avinode_devenv_install_terraform


#------------------------------------------------------------------------------
# Setup shell completions
#------------------------------------------------------------------------------
- name: Setting Terraform install present symlinks fact
  set_fact:
    _install_terraform_present_symlink_names: >-
      {{ (install_terraform_versions.installed | map('regex_replace', '^(.*)$', 'terraform\1'))
          + install_terraform_versions.symlinks | list }}
  tags:
    - avinode_devenv_install_terraform

- name: Ensure bash completions for Terraform
  ansible.builtin.template:
    dest: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/{{ _item }}.sh'
    group: '{{ avinode_devenv_default_group }}'
    mode: '0644'
    owner: '{{ avinode_devenv_default_owner }}'
    src: terraform-completion.sh.j2
  vars:
    executable_file: '{{ avinode_devenv_prefix }}/bin/{{ _item }}'
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ _install_terraform_present_symlink_names }}'
  loop_control:
    loop_var: _item
  tags:
    - avinode_devenv_install_terraform

- name: Ensure Zsh completions for Terraform
  ansible.builtin.template:
    dest: '{{ avinode_devenv_prefix }}/share/zsh/site-functions/_{{ _item }}'
    group: '{{ avinode_devenv_default_group }}'
    mode: '0644'
    owner: '{{ avinode_devenv_default_owner }}'
    src: terraform-completion.zsh.j2
  vars:
    executable_file: '{{ avinode_devenv_prefix }}/bin/{{ _item }}'
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ _install_terraform_present_symlink_names }}'
  loop_control:
    loop_var: _item
  tags:
    - avinode_devenv_install_terraform
...
