---
#------------------------------------------------------------------------------
# Remove requested items
#------------------------------------------------------------------------------
- name: Ensure Helm versions absent
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/helm{{ _helm_item }}'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_helm_versions.absent }}'
  loop_control:
    loop_var: _helm_item
  when: install_helm_versions.absent is defined
  tags:
    - avinode_devenv_install_helm

- name: Ensure Helm symlinks absent
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/{{ _helm_item }}'
    state: absent
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_helm_versions.absent_symlinks }}'
  loop_control:
    loop_var: _helm_item
  when: install_helm_versions.absent_symlinks is defined
  tags:
    - avinode_devenv_install_helm

- name: Ensure absent bash completions for Helm
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/{{ _item }}'
    state: absent
  vars:
    executable_file: '{{ avinode_devenv_prefix }}/bin/{{ _item }}'
  become: '{{ avinode_devenv_become_for_all }}'
  loop: >-
    {{ (install_helm_versions.absent | map('regex_replace', '^(.*)$', 'helm\1'))
        + install_helm_versions.absent_symlinks | list }}
  loop_control:
    loop_var: _item
  tags:
    - avinode_devenv_install_helm


#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- name: Ensure Helm versions installed
  include_tasks: process-install.yaml
  vars:
    bin_file: '{{ avinode_devenv_prefix }}/bin/helm{{ _helm_item }}'
    go_arch: '{{ avinode_devenv_go_arch }}'
    go_platform: '{{ avinode_devenv_go_platform }}'
    version: '{{ _helm_item }}'
  loop: '{{ install_helm_versions.installed }}'
  loop_control:
    loop_var: _helm_item
  when: install_helm_versions.installed is defined
  tags:
    - avinode_devenv_install_helm

- name: Ensure Helm symlinks
  ansible.builtin.file:
    path: '{{ avinode_devenv_prefix }}/bin/{{ _helm_item.key }}'
    src: '{{ avinode_devenv_prefix }}/bin/helm{{ _helm_item.value }}'
    state: link
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ install_helm_versions.symlinks | dict2items }}'
  loop_control:
    loop_var: _helm_item
  when: install_helm_versions.symlinks is defined
  tags:
    - avinode_devenv_install_helm


#------------------------------------------------------------------------------
# Setup shell completions
#------------------------------------------------------------------------------
- name: Stat helm symlink/file
  ansible.builtin.stat:
    path: '{{ avinode_devenv_prefix }}/bin/helm'
  register: _helm_symlink_stat
  tags:
    - avinode_devenv_install_helm

- name: Verify helm symlink exists
  ansible.builtin.fail:
    msg: A '{{ avinode_devenv_prefix }}/bin/helm' symlink must exists in order to configure BASH completions.
  when: not _helm_symlink_stat.stat.exists
  tags:
    - avinode_devenv_install_helm

- name: Ensure bash completions for helm
  ansible.builtin.template:
    dest: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/helm.sh'
    group: '{{ avinode_devenv_default_group }}'
    mode: '0644'
    owner: '{{ avinode_devenv_default_owner }}'
    src: helm-completion.sh.j2
  become: '{{ avinode_devenv_become_for_all }}'
  vars:
    executable_file: '{{ avinode_devenv_prefix }}/bin/helm'
    target_executables: >-
      {{ (install_helm_versions.installed | map('regex_replace', '^(.*)$', 'helm\1'))
          + install_helm_versions.symlinks | list }}
  tags:
    - avinode_devenv_install_helm
...
