---
# -----------------------------------------------------------------------------
# Load defaults
# -----------------------------------------------------------------------------
# Pattern for loading variables borrowed from:
# - https://github.com/geerlingguy/ansible-role-postgresql/blob/master/tasks/variables.yml
- name: Include OS family specific variables (Debian).
  include_vars: darwin.yaml
  when: ansible_os_family == 'Darwin'

- name: Include OS family specific variables (Debian).
  include_vars: debian.yaml
  when: ansible_os_family == 'Debian'


# -----------------------------------------------------------------------------
# Define global variables
# -----------------------------------------------------------------------------
- name: Define avinode_devenv_default_group.
  ansible.builtin.set_fact:
    avinode_devenv_default_group: '{{ __avinode_devenv_default_group }}'
  when: avinode_devenv_default_group is not defined

- name: Define avinode_devenv_default_directory_mode.
  ansible.builtin.set_fact:
    avinode_devenv_default_directory_mode: '{{ __avinode_devenv_default_directory_mode }}'
  when: avinode_devenv_default_directory_mode is not defined

- name: Define avinode_devenv_default_owner.
  ansible.builtin.set_fact:
    avinode_devenv_default_owner: '{{ __avinode_devenv_default_owner }}'
  when: avinode_devenv_default_owner is not defined

- name: Define avinode_devenv_python_path.
  ansible.builtin.set_fact:
    avinode_devenv_python_path: '{{ __avinode_devenv_python_path }}'
  when: avinode_devenv_python_path is not defined
...
