---
- name: Ensure application's Python venv directory ({{ _pyvenv_path }}).
  ansible.builtin.file:
    group: '{{ avinode_devenv_default_group }}'
    mode: '{{ avinode_devenv_default_directory_mode }}'
    owner: '{{ avinode_devenv_default_owner }}'
    path: '{{ _pyvenv_path }}'
    state: directory
  become: '{{ avinode_devenv_become_for_all }}'
  tags:
    - avinode_devenv_pyvenv_apps

- name: Ensure application installed in Python venv ({{ _pyvenv_path }}).
  ansible.builtin.pip:
    chdir: '{{ _pyvenv_path }}'
    name: '{{ _pyvenv_packages }}'
    state: '{{ _pyvenv_state }}'
    virtualenv: '{{ _pyvenv_path }}'
    virtualenv_command: '{{ _pyvenv_venv_command }}'
  become: '{{ avinode_devenv_become_for_all }}'
  tags:
    - avinode_devenv_pyvenv_apps

- name: Ensure application executable links in bin directory ({{ _pyvenv_path }}).
  ansible.builtin.file:
    dest: '{{ avinode_devenv_prefix }}/bin/{{ _pyvenv_bin_symlink_item }}'
    group: '{{ avinode_devenv_default_group }}'
    owner: '{{ avinode_devenv_default_owner }}'
    src: '{{ _pyvenv_path }}/bin/{{ _pyvenv_bin_symlink_item }}'
    state: link
  become: '{{ avinode_devenv_become_for_all }}'
  loop: '{{ _pyvenv_bin_files }}'
  loop_control:
    loop_var: _pyvenv_bin_symlink_item
    label: '{{ avinode_devenv_prefix }}/bin/{{ _pyvenv_bin_symlink_item }}'
  tags:
    - avinode_devenv_pyvenv_apps

# TODO - This is likely not a viable long term solution since Bash sourcing
# different installed versions of `register-python-argcomplet` might step on
# eachother.  This seems to work for now though.  A better solution might be to
# use a global argcomplete, issue is that it does not seems to with azure-cli.
- name: Ensure Bash completion ({{ _pyvenv_path }}).
  ansible.builtin.template:
    dest: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/python-argcomplete-{{ _pyvenv_completion_item }}.sh'
    group: '{{ avinode_devenv_default_group }}'
    mode: '0644'
    owner: '{{ avinode_devenv_default_owner }}'
    src: argcomplete.sh.j2
  become: '{{ avinode_devenv_become_for_all }}'
  vars:
    argcomplete_cmd: '{{ _pyvenv_path }}/bin/register-python-argcomplete'
    target_script: '{{ _pyvenv_completion_item }}'
  loop: '{{ _pyvenv_bin_files }}'
  loop_control:
    loop_var: _pyvenv_completion_item
    label: '{{ avinode_devenv_prefix }}/etc/bash_completion.d/python-argcomplete-{{ _pyvenv_completion_item }}.sh'
  when: _pyvenv_has_argcomplete
  tags:
    - avinode_devenv_pyvenv_apps
...
